CREATE DATABASE DB_ESCOLA;

USE DB_ESCOLA;

CREATE TABLE  TB_ESTUDANTES(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
ANO INT,
TURMA CHAR(255),
MEDIA DECIMAL(6,2),
PRIMARY KEY(ID)
);

INSERT INTO TB_ESTUDANTES (NOME,ANO,TURMA,MEDIA) VALUES ("HENRIQUE",5,"C",5.5);
INSERT INTO TB_ESTUDANTES (NOME,ANO,TURMA,MEDIA) VALUES ("ALINE",3,"B",8.5);
INSERT INTO TB_ESTUDANTES (NOME,ANO,TURMA,MEDIA) VALUES ("LARISSA",1,"A",10.0);
INSERT INTO TB_ESTUDANTES (NOME,ANO,TURMA,MEDIA) VALUES ("LUCAS",4,"A",9.75);
INSERT INTO TB_ESTUDANTES (NOME,ANO,TURMA,MEDIA) VALUES ("JORGE",3,"A",3.5);
INSERT INTO TB_ESTUDANTES (NOME,ANO,TURMA,MEDIA) VALUES ("LUARA",5,"C",7.5);
INSERT INTO TB_ESTUDANTES (NOME,ANO,TURMA,MEDIA) VALUES ("GIOVANA",2,"B",4.5);
INSERT INTO TB_ESTUDANTES (NOME,ANO,TURMA,MEDIA) VALUES ("GABRIEL",4,"B",7.0);

SELECT*FROM TB_ESTUDANTES WHERE MEDIA > 7.0;
SELECT*FROM TB_ESTUDANTES WHERE MEDIA < 7.0;

UPDATE TB_ESTUDANTES  SET MEDIA = 9.0 WHERE ID = 4;

SELECT*FROM TB_ESTUDANTES;

