-- EXERCÍCIO 6 - LISTA 2 DB

CREATE DATABASE DB_CURSO_DA_MINHA_VIDA;
USE  DB_CURSO_DA_MINHA_VIDA;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
AREA VARCHAR(255) NOT NULL,
PERIODO VARCHAR(255) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE TB_CURSOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
PRECO DECIMAL(6,2),
VAGAS INT NOT NULL,
HORAS_TOTAL INT,
CATEGORIA_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY(CATEGORIA_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS (AREA,PERIODO) VALUES ("CIENCIAS DA SAUDE","INTEGRAL");
INSERT INTO TB_CATEGORIAS (AREA,PERIODO) VALUES ("CIENCIAS HUMANAS","NOTURNO");
INSERT INTO TB_CATEGORIAS (AREA,PERIODO) VALUES ("CIENCIAS EXATAS","INTEGRAL");
INSERT INTO TB_CATEGORIAS (AREA,PERIODO) VALUES ("LINGUISTICA","MANHA");
INSERT INTO TB_CATEGORIAS (AREA,PERIODO) VALUES ("ENGENHARIA","INTEGRAL");

INSERT INTO TB_CURSOS (NOME,PRECO,VAGAS,HORAS_TOTAL,CATEGORIA_ID) VALUES ("ENFERMAGEM",1200.00,80,4000,1);
INSERT INTO TB_CURSOS (NOME,PRECO,VAGAS,HORAS_TOTAL,CATEGORIA_ID) VALUES ("ECONOMIA",899.99,55,3060,2);
INSERT INTO TB_CURSOS (NOME,PRECO,VAGAS,HORAS_TOTAL,CATEGORIA_ID) VALUES ("SISTEMAS DA INFORMACAO",300.00,40,1560,3);
INSERT INTO TB_CURSOS (NOME,PRECO,VAGAS,HORAS_TOTAL,CATEGORIA_ID) VALUES ("ITALIANO",820.00,20,700,4);
INSERT INTO TB_CURSOS (NOME,PRECO,VAGAS,HORAS_TOTAL,CATEGORIA_ID) VALUES ("ENGENHARIA MECANICA",1766.68,40,3600,5);
INSERT INTO TB_CURSOS (NOME,PRECO,VAGAS,HORAS_TOTAL,CATEGORIA_ID) VALUES ("ENGENHARIA DA COMPUTACAO",499.89,30,3200,5);
INSERT INTO TB_CURSOS (NOME,PRECO,VAGAS,HORAS_TOTAL,CATEGORIA_ID) VALUES ("RELACOES INTERNACIONAIS",657.87,50,3120,2);
INSERT INTO TB_CURSOS (NOME,PRECO,VAGAS,HORAS_TOTAL,CATEGORIA_ID) VALUES ("MEDICINA",5000.00,80,6000,1);

SELECT*FROM TB_CURSOS WHERE PRECO > 500.00;
SELECT*FROM TB_CURSOS WHERE PRECO >= 600.00 AND PRECO <= 1000;
SELECT*FROM TB_CURSOS WHERE NOME LIKE "%J%";
SELECT*FROM TB_CURSOS INNER JOIN TB_CATEGORIAS ON TB_CURSOS.CATEGORIA_ID = TB_CATEGORIAS.ID;
SELECT*FROM TB_CURSOS INNER JOIN TB_CATEGORIAS ON TB_CURSOS.CATEGORIA_ID = TB_CATEGORIAS.ID WHERE TB_CATEGORIAS.AREA = "CIENCIAS HUMANAS";