-- EXERCÍCIO 2 - LISTA 2 BD

CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
TAMANHO VARCHAR(255),
PRECO DECIMAL(6,2),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PIZZAS(
ID BIGINT AUTO_INCREMENT,
SABOR VARCHAR(255),
QTPIZZAS INT,
BORDA  VARCHAR(255),
OBSERVACAO VARCHAR(255),
CATEGORIA_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY(CATEGORIA_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS (TAMANHO,PRECO) VALUES ("BROTINHO",29.99);
INSERT INTO TB_CATEGORIAS (TAMANHO,PRECO) VALUES ("PEQUENO",35.99);
INSERT INTO TB_CATEGORIAS (TAMANHO,PRECO) VALUES ("MEDIO",45.89);
INSERT INTO TB_CATEGORIAS (TAMANHO,PRECO) VALUES ("GRANDE",57.55);
INSERT INTO TB_CATEGORIAS (TAMANHO,PRECO) VALUES ("EXTRA GRANDE",89.99);

INSERT INTO TB_PIZZAS (SABOR,QTPIZZAS,BORDA,OBSERVACAO,CATEGORIA_ID) VALUES ("CALABRESA",1,"COM RECHEIO","SEM OBSERVACOES",3);
INSERT INTO TB_PIZZAS (SABOR,QTPIZZAS,BORDA,OBSERVACAO,CATEGORIA_ID) VALUES ("MUSSARELA",1,"SEM RECHEIO","NÃO COLOCAR AZEITONA",2);
INSERT INTO TB_PIZZAS (SABOR,QTPIZZAS,BORDA,OBSERVACAO,CATEGORIA_ID) VALUES ("BAURU",1,"COM RECHEIO","SEM OBSERVACOES",5);
INSERT INTO TB_PIZZAS (SABOR,QTPIZZAS,BORDA,OBSERVACAO,CATEGORIA_ID) VALUES ("PORTUGUESA",1,"SEM RECHEIO","CAPRICHAR NO CATUPIRY",1);
INSERT INTO TB_PIZZAS (SABOR,QTPIZZAS,BORDA,OBSERVACAO,CATEGORIA_ID) VALUES ("BAIANA",1,"SEM RECHEIO","TIRAR TOMATES",4);
INSERT INTO TB_PIZZAS (SABOR,QTPIZZAS,BORDA,OBSERVACAO,CATEGORIA_ID) VALUES ("BRÓCOLIS COM CATUPIRY E BACON",1,"SEM RECHEIO","SEM OBSERVACOES",2);
INSERT INTO TB_PIZZAS (SABOR,QTPIZZAS,BORDA,OBSERVACAO,CATEGORIA_ID) VALUES ("NAPOLITANA",1,"SEM RECHEIO","SEM OBSERVACOES",1);
INSERT INTO TB_PIZZAS (SABOR,QTPIZZAS,BORDA,OBSERVACAO,CATEGORIA_ID) VALUES ("MARGUERITA",1,"SEM RECHEIO","SEM OBSERVACOES",5);

SELECT*FROM TB_CATEGORIAS WHERE PRECO > 45.00;
SELECT*FROM TB_CATEGORIAS WHERE PRECO >= 50.00 AND PRECO <= 100.00;
SELECT*FROM TB_PIZZAS  WHERE SABOR LIKE "%M%";
SELECT*FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID;
SELECT*FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID WHERE TB_CATEGORIAS.TAMANHO = "BROTINHO";